Repository cse110-fa21-group1/-cse110-fa21-group1, pull requests merged in 2021-11, with the labels that each got.

#46 Create Javascript docs automatically
  .github/workflows/JavaScriptDocs.yml
Labels: enhancement

#54 Made adjustments to navbar for now
  source/Explore.html
  source/Home.html
  source/assets/add.png
  source/assets/delete.png
  source/assets/edit.png
  source/assets/home.png
  source/assets/logout.png
  source/assets/recipe.png
  source/scripts/NavBar.js
  source/styles/navbar.css
Labels: enhancement

#45 Recipe Page essentials
  source/Recipe.html
  source/assets/heart_opaque.png
  source/assets/heart_transparent.png
  source/styles/recipe.css
Labels: enhancement

#57 Added navigation to explore
  source/scripts/NavBar.js
Labels: enhancement, Sprint-1

#38 Finished simple prototype of manage (add or edit) recipe page
  source/ManageRecipe.html
  source/scripts/ManageRecipe.js
  source/styles/ManageRecipe.css
Labels: enhancement

#61 Completed user story related issue templates
  .github/ISSUE_TEMPLATE/backend_bug.md
  .github/ISSUE_TEMPLATE/backend_feature_request.md
  .github/ISSUE_TEMPLATE/frontend_bug.md
  .github/ISSUE_TEMPLATE/frontend_feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .gitignore
Labels: documentation, Sprint-1

#70 Updates for navigation, localstorage, and CRUD
  source/Recipe.html
  source/scripts/NavBar.js
  source/scripts/Recipe.js
  source/scripts/recipeCard.js
  source/scripts/recipeDisplay.js
  source/scripts/search.js
  source/scripts/storage.js
Labels: bug, documentation, enhancement

#75 Fixed typo in backend feature request template
  .github/ISSUE_TEMPLATE/backend_feature_request.md
Labels: documentation, enhancement

#72 Udpated comments for storage.js and edit function for recipes
  source/scripts/storage.js
Labels: documentation

#81 Updated behavior of editRecipe in storage
  source/scripts/storage.js
Labels: bug, enhancement

#86 clean version of add customized recipe to local storage
  source/scripts/ManageRecipe.js
  source/styles/ManageRecipe.css
  source/styles/explore.css
  source/styles/home.css
Labels: enhancement, Sprint-1

#78 Jennifer-Fix Home Page styling errors
  source/Explore.html
  source/Home.html
  source/ManageRecipe.html
  source/Recipe.html
  source/assets/donut.png
  source/assets/logo.png
  source/styles/home.css
  source/styles/navbar.css
Labels: bug, Sprint-1

#91 FIxed a bug between new items in localstorage
  source/scripts/storage.js
Labels: bug

#93 Fixed unscrollable when navBar is showing
  source/Recipe.html
  source/styles/navbar.css
Labels: bug

#98 Fixed recipe title not populating correctly
  source/ManageRecipe.html
  source/scripts/NavBar.js
  source/scripts/deleteRecipe.js
  source/scripts/recipeCard.js
  source/scripts/recipeDisplay.js
  source/scripts/search.js
  source/styles/ManageRecipe.css
Labels: bug

#100 Added comments
  source/Explore.html
  source/Home.html
  source/ManageRecipe.html
  source/scripts/NavBar.js
Labels: enhancement

#104 Add variables for CSS colors
  source/styles/styles.css
Labels: enhancement, Sprint-2

#111 Implemented fetch recipes as baseline for creating recipes
  source/ManageRecipe.html
  source/scripts/ManageRecipe.js
  source/scripts/storage.js
  source/scripts/url.js
Labels: enhancement, Sprint-1, backend

#88 Added ability to import youtube video to a created recipe
  source/ManageRecipe.html
  source/scripts/ManageRecipe.js
  source/styles/ManageRecipe.css
  source/styles/navbar.css
Labels: enhancement

#116 Add a bit of navbar styling
  source/styles/navbar.css
Labels: enhancement, Sprint-1, frontend

#117 Fixed CSS of the entire recipe cards page.
  source/Explore.html
  source/scripts/recipeCard.js
  source/scripts/storage.js
  source/styles/explore.css
Labels: enhancement, Sprint-2

#109 create and ADR for CRUD
  specs/adrs/1119-CRUD-Process.md
  specs/adrs/CRUD-Template.png
Labels: documentation

#114 Finish Styling for Homepage for now
  source/Home.html
  source/assets/donuts.png
  source/styles/home.css
Labels: enhancement, Sprint-2, frontend

#130 Finished CSS styling of Manage Recipe Page
  source/ManageRecipe.html
  source/styles/ManageRecipe.css
  source/styles/navbar.css
  source/styles/styles.css
Labels: Sprint-2, frontend

#137 Navigation for recipe cards in explore.html and database reformatting
  source/scripts/recipeCard.js
  source/scripts/storage.js
Labels: bug, enhancement, backend, frontend

#146 Minor styling fix; Added functionality for Back to Recipe button
  source/ManageRecipe.html
  source/scripts/ManageRecipe.js
  source/styles/ManageRecipe.css
Labels: enhancement, Sprint-2, frontend

#148 Bug fixed for recipe storage
  source/scripts/storage.js
Labels: bug, Sprint-2, backend

#145 Create 112821-workflow.md
  admin/meetings/112821-workflow.md
Labels: documentation, Sprint-2

#149 Added user configurable countdown timer to recipe page
  source/Recipe.html
  source/scripts/timer.js
  source/styles/recipe.css
Labels: enhancement, Sprint-2, backend

#153 Favorite buttons are done
  source/Explore.html
  source/scripts/recipeCard.js
  source/styles/explore.css
Labels: enhancement, Sprint-2, frontend

#152 Working on Netlify deployment
  source/index.html
Labels: documentation, Sprint-2, backend

#158 Updated API access
  source/scripts/ManageRecipe.js
  source/scripts/search.js
Labels: enhancement, backend

#160 Fix for storage bug
  source/scripts/storage.js
Labels: bug, Sprint-2, backend

#162 add ADRs for using Codefactor and the reformatting of storage recipes
  specs/adrs/111921-CRUD-Process.md
  specs/adrs/112621-modify-storage.md
  specs/adrs/112821-use-Codefactor-for-git-checking.md
Labels: documentation

#165 README Updated
  README.md
Labels: enhancement, frontend

#166 Update JSDoc
  .github/workflows/JavaScriptDocs.yml
Labels: documentation, Sprint-2
