Repository cse110-fa21-group1/-cse110-fa21-group1, pull requests merged in 2021-12, with the labels that each got.

#173 Fixed bug with link
  source/index.html
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
Labels: bug, Sprint-2, backend

#177 Moduled and fixed navigations
  source/Explore.html
  source/Home.html
  source/ManageRecipe.html
  source/Recipe.html
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
  source/scripts/NavBar.js
  source/scripts/recipeCard.js
  source/scripts/url.js
Labels: bug, enhancement, Sprint-2, backend

#185 Updated JSDoc action
  .github/workflows/JavaScriptDocs.yml
  source/jsdoc.conf.json
Labels: bug, documentation

#182 Applied modular navigation & JSDoc pipeline
  .github/workflows/JavaScriptDocs.yml
  package-lock.json
  source/jsdoc.conf.json
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/scripts/linenumber.js
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/styles/jsdoc-default.css
  source/jsdocs/styles/prettify-jsdoc.css
  source/jsdocs/styles/prettify-tomorrow.css
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
  source/scripts/ManageRecipe.js
  source/scripts/NavBar.js
  source/scripts/deleteRecipe.js
  source/scripts/pin.js
  source/scripts/recipeCard.js
  source/scripts/recipeDisplay.js
  source/scripts/search.js
  source/scripts/url.js
Labels: bug, enhancement, Sprint-2, backend

#191 Fixed bug where added image would not be resized for card
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
  source/styles/explore.css
Labels: bug, frontend

#187 Updated behavior for return button on managerecipe
  .gitignore
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
  source/scripts/ManageRecipe.js
  source/scripts/recipeCard.js
  source/scripts/recipeDisplay.js
  source/scripts/storage.js
  source/scripts/url.js
Labels: bug, enhancement, Sprint-2, backend, frontend

#195 Added offset functionality for searching & toggle for recipe types
  source/Explore.html
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
  source/scripts/search.js
  source/scripts/url.js
Labels: enhancement, Sprint-2, backend

#206 Add styling to explore.html and fixed search term bug
  source/Explore.html
  source/assets/image_not_found.png
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
  source/scripts/search.js
  source/styles/explore.css
Labels: bug, enhancement, frontend

#199 Finished implementing filter pinned recipes
  source/Explore.html
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
  source/scripts/ManageRecipe.js
  source/scripts/recipeCard.js
  source/scripts/recipeDisplay.js
  source/scripts/search.js
  source/scripts/storage.js
  source/scripts/url.js
Labels: enhancement, Sprint-2, backend

#207 Improved timer accessibility, added alarm after timer finishes
  source/ManageRecipe.html
  source/Recipe.html
  source/assets/alarmsound.mp3
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
  source/scripts/ManageRecipe.js
  source/scripts/NavBar.js
  source/scripts/pin.js
  source/scripts/timer.js
  source/styles/ManageRecipe.css
  source/styles/home.css
  source/styles/navbar.css
Labels: bug, Sprint-2, backend

#209 Add styling to checkbox for pinned recipes
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
  source/styles/explore.css
Labels: Sprint-2, frontend

#213 create adrs for creating backend features and url module
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
  specs/adrs/120521-addition-for-offset-and-pin.md
  specs/adrs/120521-integrate-url-module.md
Labels: documentation, backend

#217 Show pinned search recipes and increment in per-page count
  source/Explore.html
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
  source/scripts/search.js
  source/scripts/storage.js
Labels: enhancement, Sprint-2, backend, frontend

#198 Removed unused features from Manage Recipe page, split cooking time into hr/min, added navigation to navbar logo
  source/jsdocs/ManageRecipe.js.html
  source/jsdocs/NavBar.js.html
  source/jsdocs/Recipe.html
  source/jsdocs/Recipe.js.html
  source/jsdocs/RecipeCard.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/recipeCard.js.html
  source/jsdocs/recipeDisplay.js.html
  source/jsdocs/search.js.html
  source/jsdocs/storage.js.html
  source/jsdocs/timer.js.html
  source/jsdocs/url.js.html
Labels: enhancement, Sprint-2, frontend

#220 Search message behavior updated and fix delete for pinned recipes
  source/scripts/recipeDisplay.js
  source/scripts/search.js
  source/scripts/storage.js
Labels: bug, enhancement, Sprint-2, backend

#224 Add a bunch of styling stuff
  source/Explore.html
  source/Home.html
  source/assets/image_not_found.png
  source/scripts/NavBar.js
  source/scripts/recipeCard.js
  source/scripts/search.js
  source/styles/explore.css
  source/styles/home.css
  source/styles/navbar.css
Labels: bug, Sprint-2, frontend

#228 Show message for empty search result
  source/Explore.html
  source/scripts/search.js
  source/styles/explore.css
Labels: enhancement, Sprint-2, frontend

#231 Add styling to no recipes messages
  source/Explore.html
  source/assets/search.png
  source/styles/explore.css
  source/styles/navbar.css
  source/styles/styles.css
Labels: Sprint-2, frontend

#232 Mike test search bar with end to end testing
  source/__tests__/search_test.js
  source/package-lock.json
Labels: backend

#234 Nabutabu final private meeting notes
  admin/meetings/120721-privateVideoMeeting.md
Labels: documentation

#233 More user friendly, removed unused nav buttons
  source/ManageRecipe.html
  source/styles/ManageRecipe.css
Labels: frontend

#235 Fixed portion/serving img not showing, fixed centering issue when desc too short
  source/Recipe.html
  source/styles/ManageRecipe.css
  source/styles/recipe.css
Labels: bug, frontend
